#!/bin/bash
echo begin complier, press enter;read
./bc0c test/c0/tests.c -o t1
echo press enter;read
./bc0c test/c0/area.c  -o t2
echo press enter;read
./bc0c test/c0/comment.c -o t3
echo press enter;read
./bc0c test/c0/fib.c     -o t4
echo press enter;read
./bc0c test/c0/oct_hex.c -o t5
echo press enter;read
echo begin simulate, press enter;read
./t1
echo press enter;read
./t2
echo press enter;read
./t3
echo press enter;read
./t4
echo press enter;read
./t5
echo press enter;read
rm t1 t2 t3 t4 t5
