TYPE(EXP, "exp")
TYPE(IF, "if")
TYPE(FOR, "for")
TYPE(EXPLIST, "exp_list")
TYPE(BLOCK, "block")
TYPE(BREAK, "break")
TYPE(RETURN, "return")
TYPE(CONTINUE, "continue")
TYPE(NUL, "null_stmt")
TYPE(WRITES, "writes")
TYPE(WRITEE, "writee")
TYPE(READ, "read")

